version: "3"

services:
  front_api:
    build: ./front-api/
    ports:
      - 8080:8080
    environment:
      - GRPC_HOST=localhost
      - GRPC_PORT=50051
      - TOPIC_NAME=disk_used
      - PORT=8080
  consumer:
    build: ./
    entrypoint: ["./consumer"]
    environment:
      - BROKER_HOST=localhost
      - BROKER_PORT=8426
      - BROKER_TOPIC_NAME=disk_used
      - BROKER_TOPIC_INDEX=disk_used_index
      - GRPC_ADDRESS=localhost:50051
