version: "3"

services:
  # front_api:
  #   build: ./front-api/
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - GRPC_HOST=104.196.58.169
  #     - GRPC_PORT=50051
  #     - TOPIC_NAME=disk_used
  #     - PORT=8080
  consumer:
    build: ./src/consumer/
    entrypoint: ["./wait_for_it.sh", "broker:8426", "--", "./dcm-consumer"]
    links:
      - broker
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=8426
      - BROKER_TOPIC_NAME=disk_used
      - BROKER_TOPIC_INDEX=disk_used_index
      - GRPC_ADDRESS="104.196.58.169:50051"