version: "3"

services:
  api:
    build: ./front-api/
    ports:
      - 8080:8080
  consumer:
    build: ./consumer/
    entrypoint: ["./wait_for_it.sh", "broker:8426", "--", "./dcm-consumer"]
    links:
      - broker
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=8426
      - BROKER_TOPIC_NAME=iot
      - BROKER_TOPIC_INDEX=Begin
  publisher:
    build: ./publisher/
    entrypoint: ["./wait_for_it.sh", "broker:8426", "--", "./dcm-publisher"]
    links:
      - broker
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=8426
      - BROKER_TOPIC_NAME=iot
      - BROKER_TOPIC_INDEX=Begin
  scylla:
    build: ./scylla/
    ports:
      - "9042:9042"
    environment:
      - BROADCAST-ADDRESS=127.0.0.1
      - LISTEN-ADDRESS=0.0.0.0
      - BROADCAST-RPC-ADDRESS=127.0.0.1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh"]
      interval: 5s
      timeout: 3s
      retries: 6
  broker:
    build: ./middleware/
    entrypoint: ["./wait_for_it.sh", "scylla:9042", "--", "./dcm-middleware"]
    environment:
      SERVER_PORT: 8426
      LOG_LEVEL: "DEBUG"
      SCYLLA_HOST: "scylla"
    ports: 
      - "8426:8426"
    links: 
      - "scylla"